-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 09:38:31 2024

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficinadb
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `oficinadb` ;
-- drop database `oficinadb`;
-- -----------------------------------------------------
-- Schema oficinadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficinadb` DEFAULT CHARACTER SET utf8 ;
USE `oficinadb` ;

-- -----------------------------------------------------
-- Table `oficinadb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telefone_fixo` VARCHAR(45) NULL,
  `Telefone_celular` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

alter table `Cliente` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Carro` (
  `idCarro` INT NOT NULL AUTO_INCREMENT,
  `Modelo` VARCHAR(45) NULL,
  `Ano` VARCHAR(45) NULL,
  `Cor` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCarro`, `Cliente_idCliente`),
  INDEX `fk_Carro_Cliente_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Carro_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `oficinadb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Carro` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Equipe_Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Equipe_Mecanico` (
  `idEquipe_Mecanico` INT NOT NULL AUTO_INCREMENT,
  `Codigo_equipe` VARCHAR(45) NULL,
  `Setor` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe_Mecanico`))
ENGINE = InnoDB;

alter table `Equipe_Mecanico` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Ordem_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Ordem_de_servico` (
  `idOrdem_de_servico` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  `Ordem_de_servicocol` INT NULL,
  `Valor` FLOAT(2) NULL,
  `Codigo_servico` VARCHAR(45) NULL,
  `Executada` TINYINT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Tipo_revisao_ou_conserto` TINYINT NULL,
  `Carro_idCarro` INT NOT NULL,
  `Carro_Cliente_idCliente` INT NOT NULL,
  `autorizada_pelo_cliente` TINYINT NULL,
  `Mecanico_idEquipe_Mecanico` INT NOT NULL,
  PRIMARY KEY (`idOrdem_de_servico`, `Cliente_idCliente`, `Carro_idCarro`, `Carro_Cliente_idCliente`, `Mecanico_idEquipe_Mecanico`),
  INDEX `fk_Ordem_de_servico_Cliente1_idx` (`Cliente_idCliente` ASC) ,
  INDEX `fk_Ordem_de_servico_Carro1_idx` (`Carro_idCarro` ASC, `Carro_Cliente_idCliente` ASC),
  INDEX `fk_Ordem_de_servico_Mecanico1_idx` (`Mecanico_idEquipe_Mecanico` ASC),
  CONSTRAINT `fk_Ordem_de_servico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `oficinadb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_de_servico_Carro1`
    FOREIGN KEY (`Carro_idCarro` , `Carro_Cliente_idCliente`)
    REFERENCES `oficinadb`.`Carro` (`idCarro` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_de_servico_Mecanico1`
    FOREIGN KEY (`Mecanico_idEquipe_Mecanico`)
    REFERENCES `oficinadb`.`Equipe_Mecanico` (`idEquipe_Mecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Ordem_de_servico` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Mao_de_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Mao_de_obra` (
  `idMao_de_obra` INT NOT NULL AUTO_INCREMENT,
  `Servico` VARCHAR(45) NULL,
  `Valor_hora` FLOAT(2) NULL,
  `Tempo_estimado_hora` INT NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Ordem_de_servico_idOrdem_de_servico` INT NOT NULL,
  `Ordem_de_servico_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idMao_de_obra`, `Ordem_de_servico_idOrdem_de_servico`, `Ordem_de_servico_Cliente_idCliente`),
  INDEX `fk_Mao_de_obra_Ordem_de_servico1_idx` (`Ordem_de_servico_idOrdem_de_servico` ASC, `Ordem_de_servico_Cliente_idCliente` ASC),
  CONSTRAINT `fk_Mao_de_obra_Ordem_de_servico1`
    FOREIGN KEY (`Ordem_de_servico_idOrdem_de_servico` , `Ordem_de_servico_Cliente_idCliente`)
    REFERENCES `oficinadb`.`Ordem_de_servico` (`idOrdem_de_servico` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Mao_de_obra` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Pecas` (
  `idPecas` INT NOT NULL AUTO_INCREMENT,
  `Nome_peca` VARCHAR(45) NULL,
  `Codigo_peca` VARCHAR(45) NULL,
  `Valor_peca` FLOAT(2) NULL,
  `Ordem_de_servico_idOrdem_de_servico` INT NOT NULL,
  `Ordem_de_servico_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPecas`, `Ordem_de_servico_Cliente_idCliente`),
  INDEX `fk_Pecas_Ordem_de_servico1_idx` (`Ordem_de_servico_idOrdem_de_servico` ASC, `Ordem_de_servico_Cliente_idCliente` ASC),
  CONSTRAINT `fk_Pecas_Ordem_de_servico1`
    FOREIGN KEY (`Ordem_de_servico_idOrdem_de_servico` , `Ordem_de_servico_Cliente_idCliente`)
    REFERENCES `oficinadb`.`Ordem_de_servico` (`idOrdem_de_servico` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Pecas` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Mecanico_Emite_Ordem_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Mecanico_Emite_Ordem_de_servico` (
  `Mecanico_idMecanico` INT NOT NULL AUTO_INCREMENT,
  `Ordem_de_servico_idOrdem_de_servico` INT NOT NULL,
  `Ordem_de_servico_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Mecanico_idMecanico`, `Ordem_de_servico_idOrdem_de_servico`, `Ordem_de_servico_Cliente_idCliente`),
  INDEX `fk_Mecanico_has_Ordem_de_servico_Ordem_de_servico1_idx` (`Ordem_de_servico_idOrdem_de_servico` ASC, `Ordem_de_servico_Cliente_idCliente` ASC),
  INDEX `fk_Mecanico_has_Ordem_de_servico_Mecanico1_idx` (`Mecanico_idMecanico` ASC) ,
  CONSTRAINT `fk_Mecanico_has_Ordem_de_servico_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `oficinadb`.`Equipe_Mecanico` (`idEquipe_Mecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_has_Ordem_de_servico_Ordem_de_servico1`
    FOREIGN KEY (`Ordem_de_servico_idOrdem_de_servico` , `Ordem_de_servico_Cliente_idCliente`)
    REFERENCES `oficinadb`.`Ordem_de_servico` (`idOrdem_de_servico` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Mecanico_Emite_Ordem_de_servico` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Pecas_has_Ordem_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Pecas_has_Ordem_de_servico` (
  `Pecas_idPecas` INT NOT NULL AUTO_INCREMENT,
  `Ordem_de_servico_idOrdem_de_servico` INT NOT NULL,
  `Ordem_de_servico_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Pecas_idPecas`, `Ordem_de_servico_idOrdem_de_servico`, `Ordem_de_servico_Cliente_idCliente`),
  INDEX `fk_Pecas_has_Ordem_de_servico_Ordem_de_servico1_idx` (`Ordem_de_servico_idOrdem_de_servico` ASC, `Ordem_de_servico_Cliente_idCliente` ASC),
  INDEX `fk_Pecas_has_Ordem_de_servico_Pecas1_idx` (`Pecas_idPecas` ASC),
  CONSTRAINT `fk_Pecas_has_Ordem_de_servico_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `oficinadb`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pecas_has_Ordem_de_servico_Ordem_de_servico1`
    FOREIGN KEY (`Ordem_de_servico_idOrdem_de_servico` , `Ordem_de_servico_Cliente_idCliente`)
    REFERENCES `oficinadb`.`Ordem_de_servico` (`idOrdem_de_servico` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Pecas_has_Ordem_de_servico` auto_increment=1;


-- -----------------------------------------------------
-- Table `oficinadb`.`Ordem_de_servico_has_Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Ordem_de_servico_has_Pecas` (
  `Ordem_de_servico_idOrdem_de_servico` INT NOT NULL AUTO_INCREMENT,
  `Ordem_de_servico_Cliente_idCliente` INT NOT NULL,
  `Pecas_idPecas` INT NOT NULL,
  PRIMARY KEY (`Ordem_de_servico_idOrdem_de_servico`, `Ordem_de_servico_Cliente_idCliente`, `Pecas_idPecas`),
  INDEX `fk_Ordem_de_servico_has_Pecas_Pecas1_idx` (`Pecas_idPecas` ASC),
  INDEX `fk_Ordem_de_servico_has_Pecas_Ordem_de_servico1_idx` (`Ordem_de_servico_idOrdem_de_servico` ASC, `Ordem_de_servico_Cliente_idCliente` ASC),
  CONSTRAINT `fk_Ordem_de_servico_has_Pecas_Ordem_de_servico1`
    FOREIGN KEY (`Ordem_de_servico_idOrdem_de_servico` , `Ordem_de_servico_Cliente_idCliente`)
    REFERENCES `oficinadb`.`Ordem_de_servico` (`idOrdem_de_servico` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_de_servico_has_Pecas_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `oficinadb`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Ordem_de_servico_has_Pecas` auto_increment=1;

-- -----------------------------------------------------
-- Table `oficinadb`.`Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficinadb`.`Mecanicos` (
  `idMecanicos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Codigo` VARCHAR(45) NULL,
  `Equipe_Mecanico_idEquipe_Mecanico` INT NOT NULL,
  PRIMARY KEY (`idMecanicos`, `Equipe_Mecanico_idEquipe_Mecanico`),
  INDEX `fk_Mecanicos_Equipe_Mecanico1_idx` (`Equipe_Mecanico_idEquipe_Mecanico` ASC),
  CONSTRAINT `fk_Mecanicos_Equipe_Mecanico1`
    FOREIGN KEY (`Equipe_Mecanico_idEquipe_Mecanico`)
    REFERENCES `oficinadb`.`Equipe_Mecanico` (`idEquipe_Mecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Mecanicos` auto_increment=1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
