-- MySQL Script generated by MySQL Workbench 
-- Tue Jul  9 14:52:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Criação de banco de dados num cenário de E-commerce

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- drop database ecommerce;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8;
USE `ecommerce`;

-- -----------------------------------------------------
-- Table `ecommerce`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome_completo` VARCHAR(45) NULL,
  `contato` CHAR(10) NULL,
  `perfil` VARCHAR(45) NULL,
  `endereco` VARCHAR(100),
  `data_nascimento` DATE,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Nome_completo_UNIQUE` (`Nome_completo` ASC))
ENGINE = InnoDB;

alter table `Cliente` auto_increment=1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `classification_kids` BOOL,
  `descricao` VARCHAR(45) NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

alter table `Produto` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `Descricao` VARCHAR(255) NULL,
  `Titulo_do_pedido` VARCHAR(45) NULL,
  `Tipo_de_problema` ENUM('Software', 'Hardware') NULL,
  `Prioridade` ENUM('Baixa', 'Media', 'Alta') NULL DEFAULT 'Baixa',
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Cliente2_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Pedido_Cliente2`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommerce`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Pedido` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razao_Social` VARCHAR(45) NULL,
  `CNPJ` CHAR(15) NOT NULL,
  `contato` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC))
ENGINE = InnoDB;

alter table `Fornecedor` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_fornecedor` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Fornecedor_has_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC),
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `ecommerce`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Produto_fornecedor` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

alter table `Estoque` auto_increment=1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_em_Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_em_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Localizacao` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC),
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `ecommerce`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Produto_em_estoque` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Produto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produto_pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Status` ENUM('disponivel', 'sem_estoque') NULL DEFAULT 'disponivel',
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC),
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ecommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


alter table `Produto_pedido` auto_increment=1;


-- -----------------------------------------------------
-- Table `ecommerce`.`Terceiro_Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Terceiro_Vendedor` (
  `idTerceiro_Vendedor` INT NOT NULL AUTO_INCREMENT,
  `Razao_Social` VARCHAR(45) NOT NULL COMMENT 'constrain',
  `Local` VARCHAR(45) NULL,
  `Nome_Fantasia` VARCHAR(45) NULL,
  `CNPJ` CHAR(50) NULL,
  `CPF` CHAR(50) NULL,
  PRIMARY KEY (`idTerceiro_Vendedor`),
  UNIQUE INDEX `Razao_Social_UNIQUE` (`Razao_Social` ASC),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;

ALTER TABLE `ecommerce`.`Terceiro_Vendedor` MODIFY COLUMN `CNPJ` CHAR(50);
ALTER TABLE `ecommerce`.`Terceiro_Vendedor` MODIFY COLUMN `CPF` CHAR(50);
alter table `Terceiro_Vendedor` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Produtos_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produtos_vendedor` (
  `idPseller` INT NOT NULL AUTO_INCREMENT,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`idPseller`, `Produto_idProduto`),
  INDEX `fk_Terceiro_Vendedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Terceiro_Vendedor_has_Produto_Terceiro_Vendedor1_idx` (`idPseller` ASC),
  CONSTRAINT `fk_Terceiro_Vendedor_has_Produto_Terceiro_Vendedor1`
    FOREIGN KEY (`idPseller`)
    REFERENCES `ecommerce`.`Terceiro_Vendedor` (`idTerceiro_Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro_Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommerce`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Produtos_vendedor` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `Setor` VARCHAR(45) NULL,
  `Matricula` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idResponsavel`),
  UNIQUE INDEX `Matricula_UNIQUE` (`Matricula` ASC))
ENGINE = InnoDB;

alter table `Responsavel` auto_increment=1;

-- -----------------------------------------------------
-- Table `ecommerce`.`Pedido_gerado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Pedido_gerado` (
  `Pedido_idPedido` INT NOT NULL,
  `Responsavel_idResponsavel` INT NOT NULL,
  `Setor_responsavel` VARCHAR(45) NULL DEFAULT 'Help desk',
  `Comentarios` VARCHAR(45) NULL,
  `Setor_encaminhado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Responsavel_idResponsavel`),
  INDEX `fk_Pedido_has_Responsavel_Responsavel1_idx` (`Responsavel_idResponsavel` ASC),
  INDEX `fk_Pedido_has_Responsavel_Pedido1_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Pedido_has_Responsavel_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ecommerce`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Responsavel_Responsavel1`
    FOREIGN KEY (`Responsavel_idResponsavel`)
    REFERENCES `ecommerce`.`Responsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Pedido_gerado` auto_increment=1;
-- -----------------------------------------------------
-- Table `ecommerce`.`Ordem_de_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Ordem_de_Servico` (
  `idOrdem_de_Servico` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Prioridade` VARCHAR(45) NULL,
  `Pedido_has_Responsavel_Pedido_idPedido` INT NOT NULL,
  `Pedido_has_Responsavel_Responsavel_idResponsavel` INT NOT NULL,
  PRIMARY KEY (`idOrdem_de_Servico`),
  INDEX `fk_Ordem_de_Servico_Pedido_has_Responsavel1_idx` (`Pedido_has_Responsavel_Pedido_idPedido` ASC, `Pedido_has_Responsavel_Responsavel_idResponsavel` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_de_Servico_Pedido_has_Responsavel1`
    FOREIGN KEY (`Pedido_has_Responsavel_Pedido_idPedido`, `Pedido_has_Responsavel_Responsavel_idResponsavel`)
    REFERENCES `ecommerce`.`Pedido_gerado` (`Pedido_idPedido`, `Responsavel_idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table `Ordem_de_Servico` auto_increment=1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
